/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Fariz
 */
public class Tugas2Frame extends javax.swing.JFrame {

    /**
     * Creates new form Tugas2Frame
     */
    public Tugas2Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tbHarga1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tbHarga2 = new javax.swing.JTextField();
        tbDiskon = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        tbHarga3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Barang 1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 40, 100, 40);
        getContentPane().add(tbHarga1);
        tbHarga1.setBounds(150, 40, 190, 40);

        jLabel2.setText("Barang 2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 90, 100, 40);
        getContentPane().add(tbHarga2);
        tbHarga2.setBounds(150, 90, 190, 40);
        getContentPane().add(tbDiskon);
        tbDiskon.setBounds(150, 190, 190, 40);

        jLabel3.setText("Barang 3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 140, 100, 40);

        jLabel4.setText("Diskon");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 190, 100, 40);

        jButton1.setText("Proses");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(150, 250, 190, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Total Bayar");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 294, 90, 30);

        textArea.setColumns(20);
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 330, 310, 130);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Harga");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 20, 80, 30);
        getContentPane().add(tbHarga3);
        tbHarga3.setBounds(150, 140, 190, 40);

        setBounds(0, 0, 385, 512);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int barang1 = Integer.parseInt(tbHarga1.getText());
        int barang2 = Integer.parseInt(tbHarga2.getText());
        int barang3 = Integer.parseInt(tbHarga3.getText());
        int diskon = Integer.parseInt(tbDiskon.getText());
       
        
        
        textArea.setText("Harga barang 1 : "+barang1+
                        "\nHarga barang 2 : "+ barang2+
                        "\nHarga barang 3 : "+ barang3+
                        "\nDiskon : "+diskon+
                        "\nTotal Harga : "+(barang1+barang2+barang3)+
                        "\nDengan Diskon : "+ (barang1 * diskon/100 + barang2 * diskon/100 + barang3 * diskon/100)); 
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tugas2Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tugas2Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tugas2Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tugas2Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tugas2Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tbDiskon;
    private javax.swing.JTextField tbHarga1;
    private javax.swing.JTextField tbHarga2;
    private javax.swing.JTextField tbHarga3;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
}
